%Reward Scheme - Player1 wins Reward = 1
%Player2 wins Rewards = -1
%If draw reward = 0
function [Reward, Winner, TerminalState] = RewardCalc(Board, Next_state)
TerminalState = 0;
if((Board(1) == 1 && Board(5) ==1 && Board(9) == 1) || ...
        (Board(3) == 1 && Board(5) == 1 && Board(7) == 1) || ...
            (Board(1) == 1 && Board(2) == 1 && Board(3) == 1) || ...
                (Board(4) == 1 && Board(5) == 1 && Board(6) == 1) || ...
                    (Board(7) == 1 && Board(8) == 1 && Board(9) == 1) || ...
                        (Board(1) == 1 && Board(4) == 1 && Board(7) == 1) || ...
                            (Board(2) == 1 && Board(5) == 1 && Board(8) == 1) || ...
                                (Board(3) == 1 && Board(6) == 1 && Board(9) == 1)) %player 1 wins
                            Reward = 1;
                            Winner = 1;
                            TerminalState = 1;
elseif((Board(1) == 2 && Board(5) ==2 && Board(9) == 2) || ...
        (Board(3) == 2 && Board(5) == 2 && Board(7) == 2) || ...
            (Board(1) == 2 && Board(2) == 2 && Board(3) == 2) || ...
                (Board(4) == 2 && Board(5) == 2 && Board(6) == 2) || ...
                    (Board(7) == 2 && Board(8) == 2 && Board(9) == 2) || ...
                        (Board(1) == 2 && Board(4) == 2 && Board(7) == 2) || ...
                            (Board(2) == 2 && Board(5) == 2 && Board(8) == 2) || ...
                                (Board(3) == 2 && Board(6) == 2 && Board(9) == 2)) %Player 2 wins
                            Reward = -1;
                            Winner = 2;
                            TerminalState = 1;
elseif(size(find(Board == 0),2) == 0) %Draw
    Reward = 0;
    TerminalState = 1;
    Winner = 3;
else
    Reward = 0;
    Winner = 0;
    TerminalState = 0;
end

end
